<?php
/**
 * Primary Teeth by Trev atelier homepage.
 *
 * @package TeethByTrev
 */
get_header();

$cities = array( 'Beverly Hills', 'New York', 'Atlanta', 'Houston', 'Miami', 'Washington D.C.', 'Tampa', 'Memphis' );
$stats  = array(
	array( 'value' => '10', 'suffix' => '+', 'label' => 'Years in Practice' ),
	array( 'value' => '8', 'suffix' => '', 'label' => 'Cities Served' ),
	array( 'value' => '5000', 'suffix' => '+', 'label' => 'Smiles Transformed' ),
	array( 'value' => '100', 'suffix' => '%', 'label' => 'Care, Every Visit' ),
);
$cases = array(
	array( 'index' => '01', 'title' => 'The Porcelain Veneer', 'subtitle' => 'Where artistry meets engineering', 'note' => "A hand-layered ceramic restoration tuned to the patient's complexion and lip dynamics — translucency at the edge, warmth at the core.", 'image' => 'gallery/trev-veneer-craft.jpg' ),
	array( 'index' => '02', 'title' => 'Full-Mouth Rehabilitation', 'subtitle' => 'Reconstruction · function & form', 'note' => 'Rebuilding a collapsed bite into a balanced, youthful smile — engineered for the jaw, finished for the eye.', 'image' => 'gallery/trev-scan-suite.jpg' ),
	array( 'index' => '03', 'title' => 'The Implant Restoration', 'subtitle' => 'Small in size, built to last', 'note' => 'A titanium foundation crowned in custom ceramic, placed so precisely that the result disappears into the natural arch.', 'image' => 'gallery/trev-intraoral-scan.jpg' ),
	array( 'index' => '04', 'title' => 'General Dentistry & Hygiene', 'subtitle' => 'The foundation of every smile', 'note' => 'Cleanings, exams, and preventive care performed with the same precision as the artistry — because a beautiful smile begins with a healthy one.', 'image' => 'gallery/trev-consult-blue.jpg' ),
);
$outlets = array( 'SMILE: LA', 'Zeus Network', 'TMZ', 'Yahoo', 'Black Enterprise', 'The Source', 'AllHipHop', 'HotNewHipHop', 'The Hype Magazine', 'Respect Magazine' );
$ritual = array(
	array( 'index' => 'I', 'title' => 'The Consultation', 'note' => 'We begin in conversation — studying your face, your bite, and the smile you imagine. Nothing is templated.' ),
	array( 'index' => 'II', 'title' => 'The Design', 'note' => 'A bespoke blueprint, previewed before a single tooth is touched. Proportion, translucency, and line are drawn to your features.' ),
	array( 'index' => 'III', 'title' => 'The Craft', 'note' => 'Each restoration is hand-layered and refined under magnification — ceramic worked like fine material until it disappears.' ),
	array( 'index' => 'IV', 'title' => 'The Reveal', 'note' => 'The finished smile is placed, balanced, and polished. The result looks not done, but inevitable — as though it was always yours.' ),
);
$services = array(
	array( 'label' => 'Porcelain Veneers', 'meta' => 'Cosmetic', 'image' => 'gallery/trev-veneer-craft.jpg' ),
	array( 'label' => 'Dental Implants', 'meta' => 'Restorative', 'image' => 'gallery/trev-intraoral-scan.jpg' ),
	array( 'label' => 'Smile Design', 'meta' => 'Bespoke', 'image' => 'gallery/trev-smile-design.jpg' ),
	array( 'label' => 'Full-Mouth Rehabilitation', 'meta' => 'Reconstruction', 'image' => 'gallery/trev-scan-suite.jpg' ),
	array( 'label' => 'Professional Whitening', 'meta' => 'Refinement', 'image' => 'stock/after-smile.jpg' ),
	array( 'label' => 'General Dentistry & Hygiene', 'meta' => 'Foundation', 'image' => 'gallery/trev-consult-blue.jpg' ),
);
$quotes = array(
	array( 'quote' => "I hid my smile for fifteen years. Dr. Trev gave me back something I didn't know I'd lost — myself.", 'name' => 'Maya R.', 'detail' => 'Smile makeover' ),
	array( 'quote' => 'It never felt clinical. It felt like someone finally saw me, then made me look the way I always felt inside.', 'name' => 'Andre T.', 'detail' => 'Full-mouth rehabilitation' ),
);
?>
<main id="main-content" class="bg-onyx text-ivory">
	<section id="top" class="relative flex min-h-dvh flex-col justify-center overflow-hidden bg-onyx">
		<video class="absolute inset-0 h-full w-full object-cover opacity-30 motion-safe:animate-[heroZoom_28s_ease-in-out_infinite_alternate]" autoplay muted loop playsinline poster="<?php echo tbt_asset( 'video/trevor-hero-poster.jpg' ); ?>" aria-hidden="true"><source src="<?php echo tbt_asset( 'video/trevor-hero.mp4' ); ?>" type="video/mp4"></video>
		<div class="absolute inset-0 bg-gradient-to-b from-onyx via-onyx/70 to-onyx"></div>
		<div class="tbt-radial-vignette absolute inset-0"></div>
		<div class="pointer-events-none absolute inset-5 z-10 border border-gold/25 sm:inset-8 lg:inset-10"></div>
		<div class="relative z-20 mx-auto w-full max-w-[1600px] px-6 lg:px-12">
			<div class="mb-10 flex items-center justify-between text-[0.6rem] uppercase tracking-[0.32em] text-ivory/45"><span>N° 01</span><span class="hidden sm:block">Cosmetic Atelier — Est. Beverly Hills</span><span>Dr. Trevor J. Thomas</span></div>
			<h1 class="mx-auto max-w-5xl text-center font-serif text-[3.25rem] font-light leading-[0.98] tracking-[-0.01em] text-ivory sm:text-7xl lg:text-[7.5rem]"><span class="line-reveal"><span style="transition-delay:200ms">Where the smile</span></span><span class="line-reveal"><span style="transition-delay:340ms">becomes <span class="italic text-gold">art.</span></span></span></h1>
			<p class="reveal mx-auto mt-10 max-w-md text-center text-sm leading-relaxed tracking-wide text-ivory/55">An atelier of cosmetic &amp; implant dentistry — composing faces, restoring confidence, and finishing every smile by hand.</p>
			<div class="reveal mt-12 flex justify-center"><span class="inline-block transition-transform duration-300 ease-out will-change-transform" data-tbt-magnetic><a href="<?php echo esc_url( home_url( '/consultation/' ) ); ?>" class="group inline-flex items-center gap-4 border border-ivory/30 px-9 py-4 text-[0.66rem] uppercase tracking-[0.26em] text-ivory transition-colors duration-300 hover:border-gold hover:text-gold">Request a Consultation<span class="transition-transform duration-300 group-hover:translate-x-1">→</span></a></span></div>
		</div>
		<div class="absolute inset-x-0 bottom-8 z-20 flex justify-center"><span class="text-[0.58rem] uppercase tracking-[0.3em] text-ivory/40">Scroll to enter</span></div>
	</section>

	<div class="border-y border-ivory/10 bg-onyx py-6"><div class="flex overflow-hidden"><div class="flex shrink-0 animate-marquee whitespace-nowrap"><?php for ( $repeat = 0; $repeat < 2; ++$repeat ) : foreach ( $cities as $city ) : ?><span class="mx-8 flex items-center gap-8 font-serif text-2xl font-light text-ivory/70 sm:text-3xl"><?php echo esc_html( $city ); ?><span class="text-gold">✦</span></span><?php endforeach; endfor; ?></div></div></div>

	<section id="maison" class="bg-onyx py-32 lg:py-44"><div class="mx-auto max-w-5xl px-6 lg:px-12">
		<div class="reveal"><p class="mb-6 text-[0.6rem] uppercase tracking-[0.34em] text-gold/70">The Maison</p><h2 class="mb-12 font-serif text-4xl font-light leading-[1.05] text-ivory sm:text-5xl">Dentistry is my ministry.</h2></div>
		<p class="reveal font-serif text-3xl font-light leading-[1.35] tracking-[-0.01em] text-ivory/85 sm:text-4xl lg:text-[2.85rem]">We do not sell dentistry. We compose <span class="italic text-gold">faces</span> — reading the light of a smile, the line of a lip, the architecture beneath. Every veneer is drawn by hand, every restoration weighed against a single question: <span class="italic text-gold">does it look inevitable?</span> The finest work is the work no one can see was done.</p>
		<p class="reveal mt-10 font-serif text-2xl italic text-gold sm:text-3xl">Real people. Real problems. Real results.</p>
		<div class="reveal mt-16 flex flex-col items-start gap-7 sm:flex-row sm:items-center sm:gap-10"><div class="relative h-36 w-28 shrink-0 overflow-hidden sm:h-40 sm:w-32"><img src="<?php echo tbt_asset( 'people/dr-trev-portrait.png' ); ?>" alt="Dr. Trevor J. Thomas, DDS" class="h-full w-full object-cover object-[center_20%]" loading="lazy"><div class="pointer-events-none absolute inset-0 border border-gold/30"></div></div><div><span class="font-script block text-5xl leading-none text-gold sm:text-6xl">Dr. Trev</span><span class="mt-3 block text-[0.6rem] uppercase tracking-[0.28em] text-ivory/50">Dr. Trevor J. Thomas, DDS</span></div></div>
	</div></section>

	<section class="bg-ink py-24 lg:py-28"><div class="mx-auto grid max-w-7xl grid-cols-2 gap-y-14 px-6 lg:grid-cols-4 lg:gap-y-0 lg:px-10" data-tbt-stats><?php foreach ( $stats as $stat ) : ?><div class="text-center"><div class="font-serif text-5xl font-light tracking-tight text-ivory tabular-nums sm:text-6xl lg:text-7xl"><span data-tbt-count="<?php echo esc_attr( $stat['value'] ); ?>">0</span><span class="text-champagne"><?php echo esc_html( $stat['suffix'] ); ?></span></div><span class="mx-auto mt-5 block h-px w-10 origin-center bg-champagne/60"></span><div class="mt-4 text-[0.62rem] uppercase tracking-[0.26em] text-ivory/50"><?php echo esc_html( $stat['label'] ); ?></div></div><?php endforeach; ?></div></section>

	<section id="work" class="bg-onyx py-24 lg:py-32"><div class="mx-auto max-w-6xl px-6 lg:px-10">
		<div class="mb-16 flex items-end justify-between border-b border-ivory/10 pb-6 lg:mb-24"><div><p class="mb-4 text-[0.6rem] uppercase tracking-[0.34em] text-gold/70">Case Studies</p><h2 class="font-serif text-4xl font-light text-ivory sm:text-5xl"><span class="line-reveal"><span>Selected Work</span></span></h2></div><span class="hidden whitespace-nowrap pb-1 text-[0.6rem] uppercase tracking-[0.3em] text-ivory/40 sm:block">Cosmetic &amp; Implant Dentistry</span></div>
		<div class="space-y-24 lg:space-y-32"><?php foreach ( $cases as $i => $case ) : $reverse = 1 === $i % 2; ?><article class="reveal group grid items-center gap-12 lg:gap-16 <?php echo $reverse ? 'lg:grid-cols-[7fr_5fr]' : 'lg:grid-cols-[5fr_7fr]'; ?>"><div class="<?php echo $reverse ? 'lg:order-2' : ''; ?>"><div class="relative aspect-[4/5] overflow-hidden"><div class="absolute inset-0 overflow-hidden" data-tbt-parallax><div class="absolute inset-x-0 -top-[10%] h-[120%] will-change-transform" data-tbt-parallax-inner><img src="<?php echo tbt_asset( $case['image'] ); ?>" alt="<?php echo esc_attr( $case['title'] ); ?>" class="h-full w-full object-cover grayscale transition-[filter,transform] duration-[1.2s] ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:scale-[1.03] group-hover:grayscale-0" loading="lazy"></div></div><div class="pointer-events-none absolute inset-0 border border-gold/20"></div><div class="pointer-events-none absolute inset-0 bg-gradient-to-t from-onyx/40 to-transparent opacity-60 transition-opacity duration-700 group-hover:opacity-20"></div></div></div><div class="relative <?php echo $reverse ? 'lg:order-1' : ''; ?>"><span aria-hidden="true" class="pointer-events-none absolute -top-14 left-0 font-serif text-[7rem] font-light leading-none text-ivory/[0.05] sm:text-[9rem] lg:-top-24 lg:text-[12rem]"><?php echo esc_html( $case['index'] ); ?></span><div class="relative"><div class="flex items-center gap-5"><span class="whitespace-nowrap text-[0.62rem] uppercase tracking-[0.28em] text-gold/70"><?php echo esc_html( $case['subtitle'] ); ?></span><span class="h-px flex-1 bg-ivory/15"></span></div><h3 class="mt-6 font-serif text-3xl font-light leading-[1.08] text-ivory transition-colors duration-500 group-hover:text-champagne sm:text-4xl lg:text-5xl"><?php echo esc_html( $case['title'] ); ?></h3><p class="mt-6 max-w-md text-sm leading-relaxed text-ivory/55 sm:text-base"><?php echo esc_html( $case['note'] ); ?></p></div></div></article><?php endforeach; ?></div>
	</div></section>

	<section class="relative isolate overflow-hidden bg-ink py-28 lg:py-40"><div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="reveal max-w-2xl"><p class="eyebrow mb-6 flex items-center gap-3 text-champagne"><span class="tabular-nums opacity-80">04</span><span class="h-px w-8 bg-current opacity-50" aria-hidden="true"></span><span>Trusted By</span></p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ivory sm:text-5xl">The dentist the stars come to.</h2><span class="accent-line mt-8"></span><p class="mt-8 max-w-xl text-base leading-relaxed text-ivory/70 sm:text-lg">Star of <span class="text-champagne">SMILE: LA</span>, and the Hollywood smile behind some of music and entertainment's most recognizable faces — designed with the same care given to every patient who sits in the chair.</p></div><div class="mt-16 border-t border-ivory/15 pt-10"><p class="eyebrow mb-8 text-gold/70">As Seen On</p><ul class="flex flex-wrap items-center gap-x-12 gap-y-6"><?php foreach ( $outlets as $outlet ) : ?><li class="reveal font-serif text-2xl font-light text-ivory/60 transition-colors duration-300 hover:text-ivory sm:text-3xl"><?php echo esc_html( $outlet ); ?></li><?php endforeach; ?></ul></div></div></section>

	<section class="border-t border-ivory/10 bg-onyx py-24 lg:py-32"><div class="mx-auto max-w-[1600px] px-6 lg:px-12"><div class="mb-16 flex items-end justify-between border-b border-ivory/10 pb-6"><h2 class="font-serif text-4xl font-light text-ivory sm:text-5xl"><span class="line-reveal"><span>The Ritual</span></span></h2><span class="text-[0.6rem] uppercase tracking-[0.3em] text-ivory/40">Four Movements</span></div><div class="grid gap-x-12 gap-y-14 sm:grid-cols-2 lg:grid-cols-4"><?php foreach ( $ritual as $step ) : ?><div class="reveal"><div class="flex h-full flex-col border-t border-gold/25 pt-6"><span class="font-serif text-5xl font-light leading-none text-gold/40"><?php echo esc_html( $step['index'] ); ?></span><h3 class="mt-6 font-serif text-2xl font-light text-ivory"><?php echo esc_html( $step['title'] ); ?></h3><p class="mt-4 text-sm leading-relaxed text-ivory/55"><?php echo esc_html( $step['note'] ); ?></p></div></div><?php endforeach; ?></div></div></section>

	<section id="atelier" class="relative bg-onyx py-24 lg:py-32" data-tbt-services><div class="mx-auto max-w-[1600px] px-6 lg:px-12"><div class="mb-16 flex items-end justify-between border-b border-ivory/10 pb-6"><h2 class="font-serif text-4xl font-light text-ivory sm:text-5xl"><span class="line-reveal"><span>The Atelier</span></span></h2><span class="text-[0.6rem] uppercase tracking-[0.3em] text-ivory/40">Disciplines</span></div><div class="tbt-service-preview pointer-events-none fixed left-0 top-0 z-30 hidden h-72 w-56 opacity-0 transition-opacity duration-500 lg:block" aria-hidden="true"><?php foreach ( $services as $i => $service ) : ?><div class="absolute inset-0 overflow-hidden opacity-0 transition-all duration-500" data-tbt-service-image="<?php echo esc_attr( (string) $i ); ?>"><img src="<?php echo tbt_asset( $service['image'] ); ?>" alt="" class="h-full w-full object-cover"><div class="absolute inset-0 border border-gold/30"></div></div><?php endforeach; ?></div><ul><?php foreach ( $services as $i => $service ) : ?><li class="reveal"><a href="#contact" data-tbt-service="<?php echo esc_attr( (string) $i ); ?>" class="group flex items-center justify-between gap-6 border-b border-ivory/10 py-7 transition-colors duration-500 lg:py-9"><span class="flex items-baseline gap-5"><span class="text-[0.7rem] tabular-nums text-gold/60"><?php echo esc_html( str_pad( (string) ( $i + 1 ), 2, '0', STR_PAD_LEFT ) ); ?></span><span class="font-serif text-3xl font-light text-ivory/75 transition-colors duration-300 group-hover:text-gold sm:text-5xl lg:text-6xl"><?php echo esc_html( $service['label'] ); ?></span></span><span class="hidden text-[0.6rem] uppercase tracking-[0.28em] text-ivory/40 transition-colors duration-300 group-hover:text-ivory/70 sm:block"><?php echo esc_html( $service['meta'] ); ?></span></a></li><?php endforeach; ?></ul></div></section>

	<section class="border-t border-ivory/10 bg-ink py-28 lg:py-40"><div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="grid gap-12 lg:grid-cols-2 lg:gap-20"><?php foreach ( $quotes as $quote ) : ?><figure class="reveal flex h-full flex-col justify-between border-t border-ivory/15 pt-10"><blockquote class="font-serif text-3xl font-light italic leading-[1.25] text-ivory sm:text-4xl">“<?php echo esc_html( $quote['quote'] ); ?>”</blockquote><figcaption class="mt-10"><span class="block font-medium text-ivory"><?php echo esc_html( $quote['name'] ); ?></span><span class="text-[0.72rem] uppercase tracking-[0.16em] text-gold/70"><?php echo esc_html( $quote['detail'] ); ?></span></figcaption></figure><?php endforeach; ?></div></div></section>

	<section id="contact" class="relative overflow-hidden bg-onyx py-32 lg:py-44"><div class="tbt-contact-glow absolute inset-0"></div><div class="relative mx-auto max-w-3xl px-6 text-center lg:px-12"><p class="reveal mb-8 text-[0.6rem] uppercase tracking-[0.34em] text-gold/70">Request a Consultation</p><h2 class="font-serif text-5xl font-light leading-[1.02] tracking-[-0.01em] text-ivory sm:text-6xl lg:text-7xl"><span class="line-reveal inline-block"><span>Begin your</span></span><br><span class="line-reveal inline-block italic text-gold"><span>commission.</span></span></h2><p class="reveal mx-auto mt-8 max-w-md text-sm leading-relaxed text-ivory/55">Consultations are by appointment and limited each month, so that every smile receives the attention of the atelier.</p><div class="reveal mt-12 flex flex-col items-center justify-center gap-5 sm:flex-row"><span class="inline-block transition-transform duration-300 ease-out will-change-transform" data-tbt-magnetic><a href="tel:+14243946159" class="inline-flex items-center gap-4 border border-gold px-9 py-4 text-[0.66rem] uppercase tracking-[0.26em] text-gold transition-colors hover:bg-gold hover:text-onyx">Call the Studio</a></span><a href="mailto:TeethByTrev@gmail.com" class="text-[0.66rem] uppercase tracking-[0.26em] text-ivory/60 transition-colors hover:text-ivory">TeethByTrev@gmail.com</a></div><address class="reveal mx-auto mt-10 text-[0.66rem] not-italic uppercase tracking-[0.26em] text-ivory/40">436 N Bedford Dr #300 · Beverly Hills, CA 90210</address></div></section>
</main>
<?php get_footer(); ?>
