<?php
/**
 * The preserved Classic Teeth by Trev homepage.
 *
 * @package TeethByTrev
 */
$GLOBALS['tbt_classic_layout'] = true;

$classic_services = array(
	array( 'no' => '01', 'title' => 'Smile Makeovers', 'body' => 'A fully bespoke redesign of your smile — proportion, shade, and character tailored to your face and personality.', 'image' => 'stock/service-smile-makeover.jpg', 'alt' => 'Dr. Trevor J. Thomas presenting a smile makeover plan to a patient', 'position' => 'object-top' ),
	array( 'no' => '02', 'title' => 'Porcelain Veneers', 'body' => 'Hand-finished ceramic artistry that corrects shape, color, and alignment with natural, light-catching translucency.', 'image' => 'stock/service-veneers.jpg', 'alt' => 'Dr. Trevor J. Thomas hand-finishing porcelain veneers at the bench', 'position' => 'object-center' ),
	array( 'no' => '03', 'title' => 'Dental Implants', 'body' => 'Permanent, lifelike tooth replacement — engineered for function and finished for beauty.', 'image' => 'stock/service-implants.jpg', 'alt' => 'Dr. Trevor J. Thomas discussing dental implants with a patient beside a panoramic X-ray', 'position' => 'object-center' ),
	array( 'no' => '04', 'title' => 'Full-Mouth Rehabilitation', 'body' => 'Complex, life-restoring reconstruction that rebuilds health, bite, and confidence from the ground up.', 'image' => 'stock/service-full-mouth.jpg', 'alt' => 'Dr. Trevor J. Thomas performing a full-mouth rehabilitation procedure', 'position' => 'object-center' ),
);
$classic_portraits = array(
	array( 'image' => 'gallery/trev-scan-suite.jpg', 'alt' => 'Full-mouth rehabilitation plan with 3D imaging and an implant model', 'title' => 'The Treatment', 'note' => 'Planned to the detail' ),
	array( 'image' => 'gallery/trev-consult-suit.jpg', 'alt' => 'Dr. Trevor J. Thomas presenting a dental model to a patient', 'title' => 'The Consultation', 'note' => 'Your plan, personalized' ),
	array( 'image' => 'gallery/trev-veneer-craft.jpg', 'alt' => 'Dr. Trevor J. Thomas hand-finishing a porcelain veneer at the bench', 'title' => 'The Craft', 'note' => 'Hand-finished veneers' ),
	array( 'image' => 'gallery/trev-intraoral-scan.jpg', 'alt' => 'Implant components and a 3D arch rendering on screen', 'title' => 'Digital Scanning', 'note' => '3D smile design' ),
	array( 'image' => 'gallery/trev-consult-blue.jpg', 'alt' => 'The Teeth by Trev treatment studio', 'title' => 'The Studio', 'note' => 'Calm, precise, unhurried' ),
);
$classic_outlets = array( 'SMILE: LA', 'Zeus Network', 'TMZ', 'Yahoo', 'Black Enterprise', 'The Source', 'AllHipHop', 'HotNewHipHop', 'The Hype Magazine', 'Respect Magazine' );
$classic_quotes = array(
	array( 'quote' => "I hid my smile for fifteen years. Dr. Trev gave me back something I didn't know I'd lost — myself.", 'name' => 'Maya R.', 'detail' => 'Smile makeover' ),
	array( 'quote' => 'It never felt clinical. It felt like someone finally saw me, then made me look the way I always felt inside.', 'name' => 'Andre T.', 'detail' => 'Full-mouth rehabilitation' ),
);
$classic_benefits = array(
	array( 'title' => 'Plans from $0 down', 'body' => 'Begin your transformation today with low monthly payments tailored to your budget — no large upfront cost.', 'path' => 'M3 9.5h18M3 9.5A2.5 2.5 0 0 1 5.5 7h13A2.5 2.5 0 0 1 21 9.5m-18 0v7A2.5 2.5 0 0 0 5.5 19h13a2.5 2.5 0 0 0 2.5-2.5v-7M7 15.5h4' ),
	array( 'title' => 'Apply in minutes', 'body' => 'A simple, soft credit check gets you an answer fast — without affecting your score or interrupting your day.', 'path' => 'M12 7v5l3 2m6-2a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z' ),
	array( 'title' => 'Care that fits your life', 'body' => 'Stretch your investment across comfortable terms so the smile you deserve never has to wait for the perfect moment.', 'path' => 'M12 20.25S3.75 15.5 3.75 9.62A4.12 4.12 0 0 1 12 7.5a4.12 4.12 0 0 1 8.25 2.12C20.25 15.5 12 20.25 12 20.25Z' ),
);
$classic_locations = array( 'Beverly Hills', 'New York', 'Atlanta', 'Houston', 'Miami', 'Washington D.C.', 'Tampa', 'Memphis' );

get_header();
?>
<main id="main-content" class="flex-1">
	<section id="top" class="relative min-h-dvh overflow-hidden bg-ink">
		<video class="absolute inset-0 h-full w-full origin-center scale-105 object-cover motion-safe:animate-[heroZoom_24s_ease-in-out_infinite_alternate]" autoplay muted loop playsinline poster="<?php echo tbt_asset( 'video/trevor-hero-poster.jpg' ); ?>" aria-hidden="true"><source src="<?php echo tbt_asset( 'video/trevor-hero.mp4' ); ?>" type="video/mp4"></video>
		<div class="absolute inset-0 bg-gradient-to-t from-ink/90 via-ink/55 to-ink/65"></div>
		<div aria-hidden="true" class="pointer-events-none absolute inset-0 mix-blend-soft-light motion-safe:animate-sheen" style="background:radial-gradient(42% 52% at 32% 30%,rgba(184,155,110,.45),transparent 70%)"></div>
		<div aria-hidden="true" class="pointer-events-none absolute inset-0" style="background:radial-gradient(120% 110% at 50% 35%,transparent 45%,rgba(12,10,8,.6) 100%)"></div>
		<div class="relative z-10 mx-auto flex min-h-dvh max-w-7xl flex-col justify-end px-6 pb-20 pt-40 lg:px-10 lg:pb-28">
			<p class="eyebrow mb-6 text-champagne">Cosmetic &amp; Implant Dentistry</p>
			<h1 class="max-w-4xl font-serif text-[2.75rem] font-light leading-[1.05] text-ivory sm:text-6xl lg:text-7xl"><span class="line-reveal"><span>It’s not about the teeth.</span></span><span class="line-reveal"><span>It’s about the life your</span></span><span class="line-reveal"><span>smile lets you live.</span></span></h1>
			<p class="mt-8 max-w-xl text-base leading-relaxed text-ivory/80 sm:text-lg">Dr. Trevor J. Thomas crafts life-changing smiles for real people with real stories — blending artistry, precision, and a little soul into every transformation.</p>
			<div class="mt-10 flex flex-col gap-4 sm:flex-row sm:items-start"><span class="inline-block transition-transform duration-300 ease-out will-change-transform" data-tbt-magnetic><a href="https://www.diverzeent.com/tbv-inquiry/" target="_blank" rel="noopener noreferrer" class="inline-flex items-center justify-center bg-ivory px-8 py-4 text-[0.72rem] font-medium uppercase tracking-[0.2em] text-ink transition-colors duration-300 hover:bg-champagne">Book Your Consultation</a></span><a href="#gallery" class="inline-flex items-center justify-center border border-ivory/40 px-8 py-4 text-[0.72rem] font-medium uppercase tracking-[0.2em] text-ivory transition-colors duration-300 hover:border-ivory hover:bg-ivory/10">View Smile Gallery</a></div>
		</div>
		<a href="#philosophy" aria-label="Scroll to learn more" class="absolute bottom-8 left-1/2 z-10 hidden -translate-x-1/2 flex-col items-center gap-3 text-ivory/70 transition-colors hover:text-ivory lg:flex"><span class="text-[0.62rem] uppercase tracking-[0.28em]">Scroll</span><span class="relative h-14 w-px overflow-hidden bg-ivory/20"><span class="absolute inset-x-0 top-0 h-1/2 bg-gradient-to-b from-ivory to-transparent motion-safe:animate-scrollCue"></span></span></a>
	</section>

	<section id="philosophy" class="relative isolate overflow-hidden bg-ivory py-28 lg:py-40">
		<?php tbt_section_motifs( 0 ); ?>
		<div class="mx-auto grid max-w-7xl items-center gap-16 px-6 lg:grid-cols-2 lg:gap-24 lg:px-10">
			<div class="reveal"><p class="eyebrow mb-6 flex items-center gap-3"><span class="tabular-nums opacity-80">01</span><span class="h-px w-8 bg-current opacity-50"></span><span>The Philosophy</span></p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ink sm:text-5xl">Dentistry is my ministry.</h2><span class="accent-line mt-8"></span><div class="mt-8 space-y-6 text-base leading-relaxed text-stone sm:text-lg"><p>For Dr. Trev, a smile is a gateway — to confidence, to better mental health, to a fuller life. Every case begins not with a tooth, but with a person and the story they carry.</p><p>That belief has shaped a practice where world-class craftsmanship meets genuine care. The result is work that looks effortless and feels like coming home to yourself.</p></div><p class="mt-10 font-serif text-2xl italic text-gold">Real people. Real problems. Real results.</p><div class="mt-10"><span class="block font-script text-6xl leading-none text-champagne sm:text-7xl">Dr. Trev</span><span class="mt-3 block text-[0.7rem] uppercase tracking-[0.24em] text-stone">Dr. Trevor Thomas, DDS</span></div></div>
			<div class="reveal"><div class="relative"><div class="group relative aspect-[4/5] w-full overflow-hidden"><div class="img-reveal relative h-full w-full"><img src="<?php echo tbt_asset( 'people/dr-trev-portrait.png' ); ?>" alt="Dr. Trevor J. Thomas, DDS" class="h-full w-full object-contain transition-transform duration-[1.4s] group-hover:scale-105" loading="lazy"></div></div><div class="absolute -bottom-6 -left-6 hidden h-32 w-32 border border-gold/40 lg:block"></div></div></div>
		</div>
	</section>

	<section class="relative overflow-hidden bg-cream py-28 lg:py-40"><span aria-hidden="true" class="pointer-events-none absolute left-1/2 top-4 -translate-x-1/2 font-serif text-[16rem] leading-none text-gold/10 sm:text-[22rem]">“</span><div class="relative mx-auto max-w-5xl px-6 text-center lg:px-10"><div class="reveal"><p class="eyebrow mb-10">In His Words</p><blockquote class="font-serif text-3xl font-light leading-[1.22] text-ink sm:text-4xl lg:text-[3.25rem] lg:leading-[1.18]">A smile isn’t cosmetic. It’s the first thing you give the world and the last thing you forget about yourself. My work is to give people back something they thought was gone for good.</blockquote><div class="mt-12 flex items-center justify-center gap-4"><span class="h-px w-10 bg-gold/50"></span><span class="text-[0.72rem] uppercase tracking-[0.26em] text-stone">Dr. Trevor J. Thomas, DDS</span><span class="h-px w-10 bg-gold/50"></span></div></div></div></section>

	<section class="bg-ink py-24 lg:py-28"><div class="mx-auto grid max-w-7xl grid-cols-2 gap-y-14 px-6 lg:grid-cols-4 lg:gap-y-0 lg:px-10" data-tbt-stats><?php foreach ( array( array( 10, '+', 'Years in Practice' ), array( 8, '', 'Cities Served' ), array( 5000, '+', 'Smiles Transformed' ), array( 100, '%', 'Care, Every Visit' ) ) as $stat ) : ?><div class="text-center"><div class="font-serif text-5xl font-light tracking-tight text-ivory tabular-nums sm:text-6xl lg:text-7xl"><span data-tbt-count="<?php echo esc_attr( (string) $stat[0] ); ?>">0</span><span class="text-champagne"><?php echo esc_html( $stat[1] ); ?></span></div><span class="mx-auto mt-5 block h-px w-10 bg-champagne/60"></span><div class="mt-4 text-[0.62rem] uppercase tracking-[0.26em] text-ivory/50"><?php echo esc_html( $stat[2] ); ?></div></div><?php endforeach; ?></div></section>

	<section id="services" class="relative isolate overflow-hidden bg-cream py-28 lg:py-40">
		<?php tbt_section_motifs( 1 ); ?>
		<div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="reveal max-w-2xl"><p class="eyebrow mb-6 flex items-center gap-3"><span class="tabular-nums opacity-80">02</span><span class="h-px w-8 bg-current opacity-50"></span><span>The Craft</span></p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ink sm:text-5xl">Signature services, executed as artistry.</h2><span class="accent-line mt-8"></span></div><div class="mt-16 grid gap-x-8 gap-y-14 sm:grid-cols-2"><?php foreach ( $classic_services as $service ) : ?><article class="reveal group"><div class="relative aspect-[5/4] overflow-hidden"><img src="<?php echo tbt_asset( $service['image'] ); ?>" alt="<?php echo esc_attr( $service['alt'] ); ?>" class="h-full w-full object-cover <?php echo esc_attr( $service['position'] ); ?> transition-transform duration-[1.4s] group-hover:scale-105" loading="lazy"><div class="absolute inset-0 bg-ink/10 transition-opacity duration-500 group-hover:bg-ink/0"></div><span class="absolute left-5 top-5 font-serif text-2xl text-ivory/90 drop-shadow"><?php echo esc_html( $service['no'] ); ?></span></div><div class="mt-7 flex items-start justify-between gap-6 border-t border-stone/20 pt-6"><div><h3 class="font-serif text-3xl font-light text-ink"><?php echo esc_html( $service['title'] ); ?></h3><p class="mt-3 max-w-md text-base leading-relaxed text-stone"><?php echo esc_html( $service['body'] ); ?></p></div><span class="mt-2 shrink-0 text-gold">→</span></div></article><?php endforeach; ?></div></div>
	</section>

	<div class="bg-ivory py-20"><div class="reveal mx-auto flex max-w-7xl items-center justify-center gap-5 px-6 lg:px-10"><span class="h-px w-24 bg-gradient-to-r from-transparent via-gold/40 to-transparent sm:w-40"></span><span class="text-[0.7rem] text-gold/70">✦</span><span class="h-px w-24 bg-gradient-to-l from-transparent via-gold/40 to-transparent sm:w-40"></span></div></div>

	<section id="gallery" class="bg-ivory pb-28 pt-12 lg:pb-40 lg:pt-16">
		<div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="reveal flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-end"><div class="max-w-2xl"><p class="eyebrow mb-6 flex items-center gap-3"><span class="tabular-nums opacity-80">03</span><span class="h-px w-8 bg-current opacity-50"></span><span>The Smile Gallery</span></p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ink sm:text-5xl">Transformations, not just teeth.</h2><span class="accent-line mt-8"></span></div><a href="https://www.diverzeent.com/tbv-inquiry/" target="_blank" rel="noopener noreferrer" class="shrink-0 border-b border-ink pb-1 text-[0.72rem] font-medium uppercase tracking-[0.2em] text-ink transition-colors hover:border-gold hover:text-gold">Start your story</a></div>
			<div class="reveal mt-16"><div class="tbt-before-after relative aspect-[16/10] w-full overflow-hidden bg-ink" data-tbt-before-after><img src="<?php echo tbt_asset( 'stock/after-smile.jpg' ); ?>" alt="Bright, restored smile after treatment by Dr. Trevor J. Thomas" class="absolute inset-0 h-full w-full object-cover"><span class="pointer-events-none absolute right-5 top-5 z-20 bg-ink/55 px-3 py-1 text-[0.62rem] font-medium uppercase tracking-[0.22em] text-ivory">After</span><div class="absolute inset-0" style="clip-path:inset(0 50% 0 0)" data-tbt-before><img src="<?php echo tbt_asset( 'stock/before-smile.jpg' ); ?>" alt="Worn, damaged smile before treatment by Dr. Trevor J. Thomas" class="h-full w-full object-cover"><span class="pointer-events-none absolute left-5 top-5 z-20 bg-ink/55 px-3 py-1 text-[0.62rem] font-medium uppercase tracking-[0.22em] text-ivory">Before</span></div><div class="absolute inset-y-0 z-30 w-px bg-ivory" style="left:50%" data-tbt-handle><button type="button" role="slider" aria-label="Drag to compare before and after" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" class="absolute left-1/2 top-1/2 flex h-12 w-12 -translate-x-1/2 -translate-y-1/2 cursor-ew-resize items-center justify-center rounded-full bg-ivory text-ink shadow-[0_4px_24px_rgba(0,0,0,0.35)]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" class="h-5 w-5"><path d="M9 7 4 12l5 5M15 7l5 5-5 5"></path></svg></button></div></div><p class="mt-4 text-center text-[0.72rem] uppercase tracking-[0.2em] text-stone">Drag to reveal the transformation</p></div>
			<div class="mt-20"><figure class="group relative aspect-[3/2] w-full overflow-hidden sm:aspect-[2/1] lg:aspect-[5/2]"><div class="img-reveal relative h-full w-full"><img src="<?php echo tbt_asset( 'gallery/trev-exam.jpg' ); ?>" alt="Dr. Trevor J. Thomas performing a detailed examination in the Teeth by Trev studio" class="h-full w-full object-cover object-center transition-transform duration-[1.4s] group-hover:scale-105" loading="lazy"></div><div class="absolute inset-0 bg-gradient-to-t from-ink/85 via-ink/10 to-transparent opacity-80"></div><figcaption class="absolute inset-x-0 bottom-0 translate-y-2 p-6 opacity-0 transition-all duration-500 group-hover:translate-y-0 group-hover:opacity-100 lg:p-8"><span class="block font-serif text-2xl font-light text-ivory sm:text-3xl">Inside the chair</span><span class="text-[0.72rem] uppercase tracking-[0.18em] text-champagne">Precision diagnostics, every visit</span></figcaption></figure></div>
			<div class="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5"><?php foreach ( $classic_portraits as $portrait ) : ?><figure class="group relative aspect-[4/5] overflow-hidden"><div class="img-reveal relative h-full w-full"><img src="<?php echo tbt_asset( $portrait['image'] ); ?>" alt="<?php echo esc_attr( $portrait['alt'] ); ?>" class="h-full w-full object-cover object-top transition-transform duration-[1.4s] group-hover:scale-105" loading="lazy"></div><div class="absolute inset-0 bg-gradient-to-t from-ink/85 via-ink/10 to-transparent opacity-80"></div><figcaption class="absolute inset-x-0 bottom-0 translate-y-2 p-5 opacity-0 transition-all duration-500 group-hover:translate-y-0 group-hover:opacity-100"><span class="block font-serif text-xl font-light text-ivory"><?php echo esc_html( $portrait['title'] ); ?></span><span class="text-[0.66rem] uppercase tracking-[0.16em] text-champagne"><?php echo esc_html( $portrait['note'] ); ?></span></figcaption></figure><?php endforeach; ?></div>
		</div>
	</section>

	<section class="relative isolate overflow-hidden bg-ink py-28 lg:py-40"><?php tbt_section_motifs( 2 ); ?><div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="reveal max-w-2xl"><p class="eyebrow mb-6 flex items-center gap-3 text-champagne"><span class="tabular-nums opacity-80">04</span><span class="h-px w-8 bg-current opacity-50"></span><span>Trusted By</span></p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ivory sm:text-5xl">The dentist the stars come to.</h2><span class="accent-line mt-8"></span><p class="mt-8 max-w-xl text-base leading-relaxed text-ivory/70 sm:text-lg">Star of <span class="text-champagne">SMILE: LA</span>, and the Hollywood smile behind some of music and entertainment’s most recognizable faces — designed with the same care given to every patient who sits in the chair.</p></div><div class="mt-16 border-t border-ivory/15 pt-10"><p class="eyebrow mb-8 text-gold/70">As Seen On</p><ul class="flex flex-wrap items-center gap-x-12 gap-y-6"><?php foreach ( $classic_outlets as $outlet ) : ?><li class="reveal font-serif text-2xl font-light text-ivory/60 transition-colors hover:text-ivory sm:text-3xl"><?php echo esc_html( $outlet ); ?></li><?php endforeach; ?></ul></div></div></section>

	<?php tbt_experience_process(); ?>

	<section class="relative h-[70vh] min-h-[460px] overflow-hidden"><img src="<?php echo tbt_asset( 'stock/feature-bg.jpg' ); ?>" alt="Dr. Trevor J. Thomas and his assistant caring for a patient in the studio" class="absolute inset-0 h-full w-full object-cover" loading="lazy"><div class="absolute inset-0 bg-ink/45"></div><div class="relative z-10 mx-auto flex h-full max-w-4xl flex-col items-center justify-center px-6 text-center"><div class="reveal"><p class="eyebrow mb-6 text-champagne">The Standard</p><p class="font-serif text-3xl font-light leading-[1.2] text-ivory sm:text-4xl lg:text-5xl">Every detail is considered. Every result is earned. Nothing about your smile is left to chance.</p></div></div></section>

	<section class="bg-ivory py-28 lg:py-40"><div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="grid gap-12 lg:grid-cols-2 lg:gap-20"><?php foreach ( $classic_quotes as $quote ) : ?><figure class="reveal flex h-full flex-col justify-between border-t border-stone/20 pt-10"><blockquote class="font-serif text-3xl font-light italic leading-[1.25] text-ink sm:text-4xl">“<?php echo esc_html( $quote['quote'] ); ?>”</blockquote><figcaption class="mt-10"><span class="block font-medium text-ink"><?php echo esc_html( $quote['name'] ); ?></span><span class="text-[0.72rem] uppercase tracking-[0.16em] text-taupe"><?php echo esc_html( $quote['detail'] ); ?></span></figcaption></figure><?php endforeach; ?></div></div></section>

	<section id="financing" class="bg-sand py-28 lg:py-40"><div class="mx-auto grid max-w-7xl gap-14 px-6 lg:grid-cols-[1fr_0.9fr] lg:items-center lg:gap-24 lg:px-10"><div class="reveal max-w-xl"><p class="eyebrow mb-6 flex items-center gap-3"><span class="tabular-nums opacity-80">05</span><span class="h-px w-8 bg-current opacity-50"></span><span>Smile Now, Pay Later</span></p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ink sm:text-5xl lg:text-6xl">A world-class smile shouldn’t wait for the perfect moment.</h2><span class="accent-line mt-8"></span><p class="mt-8 max-w-lg text-base leading-relaxed text-stone sm:text-lg">We believe transformation should be within reach. Flexible financing and monthly payment plans make life-changing dentistry accessible — so you can begin today and pay over time.</p><a href="#consultation" class="mt-10 inline-flex items-center justify-center bg-ink px-8 py-4 text-[0.72rem] font-medium uppercase tracking-[0.2em] text-ivory transition-colors hover:bg-espresso">Explore Financing Options</a></div><div class="reveal"><div class="divide-y divide-stone/15 border-y border-stone/15"><?php foreach ( $classic_benefits as $benefit ) : ?><div class="flex gap-5 py-7"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" class="mt-1 h-7 w-7 shrink-0 text-gold"><path d="<?php echo esc_attr( $benefit['path'] ); ?>" stroke-width="1.25"></path></svg><div><h3 class="font-serif text-2xl font-light text-ink"><?php echo esc_html( $benefit['title'] ); ?></h3><p class="mt-2 max-w-sm text-[0.95rem] leading-relaxed text-stone"><?php echo esc_html( $benefit['body'] ); ?></p></div></div><?php endforeach; ?></div></div></div></section>

	<section id="consultation" class="relative isolate overflow-hidden bg-espresso py-28 text-ivory lg:py-40"><?php tbt_section_motifs( 4 ); ?><div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="grid gap-16 lg:grid-cols-2 lg:gap-24"><div class="reveal"><p class="eyebrow mb-6 text-champagne">Begin</p><h2 class="font-serif text-4xl font-light leading-[1.05] text-ivory sm:text-5xl lg:text-6xl">Book your consultation.</h2><p class="mt-8 max-w-md text-base leading-relaxed text-ivory/70 sm:text-lg">Tell us a little about your smile and what you’d love to change. Texting is the fastest way to reach the team.</p><dl class="mt-12 space-y-6 text-ivory/80"><div><dt class="eyebrow mb-2 text-champagne">Text / Call</dt><dd class="font-serif text-2xl"><a href="tel:+14243946159" class="hover:text-champagne">424-394-6159</a></dd></div><div><dt class="eyebrow mb-2 text-champagne">Email</dt><dd class="font-serif text-2xl"><a href="mailto:TeethByTrev@gmail.com" class="hover:text-champagne">TeethByTrev@gmail.com</a></dd></div><div><dt class="eyebrow mb-2 text-champagne">Flagship Studio</dt><dd class="text-base leading-relaxed">436 N Bedford Dr #300<br>Beverly Hills, CA 90210</dd></div></dl></div>
			<div class="reveal"><form action="<?php echo esc_url( home_url( '/contact/' ) ); ?>" method="get" class="space-y-6" aria-label="Consultation request"><input type="hidden" name="intent" value="new"><div class="grid gap-6 sm:grid-cols-2"><div><label for="classic-first-name" class="eyebrow mb-3 block text-champagne">First name</label><input id="classic-first-name" name="firstName" autocomplete="given-name" class="w-full border border-ivory/25 bg-transparent px-4 py-3 text-ivory focus:border-champagne focus:outline-none"></div><div><label for="classic-last-name" class="eyebrow mb-3 block text-champagne">Last name</label><input id="classic-last-name" name="lastName" autocomplete="family-name" class="w-full border border-ivory/25 bg-transparent px-4 py-3 text-ivory focus:border-champagne focus:outline-none"></div></div><div><label for="classic-email" class="eyebrow mb-3 block text-champagne">Email</label><input id="classic-email" name="email" type="email" autocomplete="email" class="w-full border border-ivory/25 bg-transparent px-4 py-3 text-ivory focus:border-champagne focus:outline-none"></div><div><label for="classic-phone" class="eyebrow mb-3 block text-champagne">Phone</label><input id="classic-phone" name="phone" type="tel" autocomplete="tel" class="w-full border border-ivory/25 bg-transparent px-4 py-3 text-ivory focus:border-champagne focus:outline-none"></div><div><label for="classic-message" class="eyebrow mb-3 block text-champagne">What would you love to change?</label><textarea id="classic-message" name="goals" rows="4" class="w-full resize-none border border-ivory/25 bg-transparent px-4 py-3 text-ivory focus:border-champagne focus:outline-none"></textarea></div><button type="submit" class="inline-flex w-full items-center justify-center bg-ivory px-8 py-4 text-[0.72rem] font-medium uppercase tracking-[0.2em] text-ink transition-colors hover:bg-champagne sm:w-auto">Request Consultation</button></form></div>
		</div><div class="reveal mt-20 border-t border-ivory/15 pt-10"><ul class="flex flex-wrap items-center gap-x-10 gap-y-3"><li class="eyebrow text-champagne">By Appointment</li><?php foreach ( $classic_locations as $location ) : ?><li class="font-serif text-xl font-light text-ivory/80"><?php echo esc_html( $location ); ?></li><?php endforeach; ?></ul></div></div>
	</section>
</main>
<?php get_footer(); ?>
