<?php
/** @package TeethByTrev */
get_header();
$cases = array(
	array( 'name' => 'Inside the Chair', 'note' => 'Precision diagnostics', 'image' => 'stock/financing-hero.jpg', 'alt' => 'A patient reviewing a panoramic X-ray and dental implant model in the studio' ),
	array( 'name' => 'The Treatment', 'note' => 'Planned to the detail', 'image' => 'gallery/trev-scan-suite.jpg', 'alt' => 'Full-mouth rehabilitation plan with 3D imaging and an implant model' ),
	array( 'name' => 'The Consultation', 'note' => 'Your plan, personalized', 'image' => 'stock/service-smile-makeover.jpg', 'alt' => 'Dr. Trevor J. Thomas presenting a smile makeover plan to a patient' ),
	array( 'name' => 'The Craft', 'note' => 'Hand-finished veneers', 'image' => 'gallery/trev-veneer-craft.jpg', 'alt' => 'Dr. Trevor J. Thomas hand-finishing a porcelain veneer at the bench' ),
	array( 'name' => 'Digital Scanning', 'note' => '3D smile design', 'image' => 'gallery/trev-intraoral-scan.jpg', 'alt' => 'Implant components and a 3D arch rendering on screen' ),
	array( 'name' => 'The Studio', 'note' => 'Calm, precise, unhurried', 'image' => 'gallery/trev-consult-blue.jpg', 'alt' => 'The Teeth by Trev treatment studio' ),
);
?>
<main id="main-content" class="bg-onyx text-ivory">
	<?php tbt_page_hero( 'The Smile Gallery', 'Transformations, not just teeth.', 'Every smile here belongs to a real person with a real story. This is the work — placed, balanced, and unmistakably theirs.', 'stock/feature-bg.jpg', 'Dr. Trevor J. Thomas and his assistant caring for a patient in the studio' ); ?>
	<section class="bg-onyx py-28 lg:py-40"><div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="reveal mx-auto max-w-2xl text-center"><p class="mb-6 text-[0.6rem] uppercase tracking-[0.34em] text-gold/70">01 — Before &amp; After</p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ivory sm:text-5xl">See the difference, side by side.</h2></div><div class="reveal mt-16"><div class="tbt-before-after relative aspect-[16/10] w-full overflow-hidden bg-ink" data-tbt-before-after><img src="<?php echo tbt_asset( 'stock/after-smile.jpg' ); ?>" alt="Bright, restored smile after treatment by Dr. Trevor J. Thomas" class="absolute inset-0 h-full w-full object-cover"><span class="pointer-events-none absolute right-5 top-5 z-20 bg-ink/55 px-3 py-1 text-[0.62rem] font-medium uppercase tracking-[0.22em] text-ivory">After</span><div class="absolute inset-0" data-tbt-before style="clip-path:inset(0 50% 0 0)"><img src="<?php echo tbt_asset( 'stock/before-smile.jpg' ); ?>" alt="Worn, damaged smile before treatment by Dr. Trevor J. Thomas" class="h-full w-full object-cover"><span class="pointer-events-none absolute left-5 top-5 z-20 bg-ink/55 px-3 py-1 text-[0.62rem] font-medium uppercase tracking-[0.22em] text-ivory">Before</span></div><div class="absolute inset-y-0 z-30 w-px bg-ivory" data-tbt-handle style="left:50%"><button type="button" role="slider" aria-label="Drag to compare before and after" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" class="absolute left-1/2 top-1/2 flex h-12 w-12 -translate-x-1/2 -translate-y-1/2 cursor-ew-resize items-center justify-center rounded-full bg-ivory text-ink shadow-[0_4px_24px_rgba(0,0,0,0.35)]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" class="h-5 w-5"><path d="M9 7 4 12l5 5M15 7l5 5-5 5"></path></svg></button></div></div><p class="mt-4 text-center text-[0.72rem] uppercase tracking-[0.2em] text-ivory/45">Drag to reveal the transformation</p></div></div></section>
	<section class="border-t border-ivory/10 bg-ink py-28 lg:py-40"><div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="reveal max-w-2xl"><p class="mb-6 text-[0.6rem] uppercase tracking-[0.34em] text-gold/70">02 — The Cases</p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ivory sm:text-5xl">A few of the smiles we’ve had the honor to craft.</h2></div><div class="mt-16 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><?php foreach ( $cases as $case ) : ?><figure class="reveal group relative aspect-[4/5] overflow-hidden"><img src="<?php echo tbt_asset( $case['image'] ); ?>" alt="<?php echo esc_attr( $case['alt'] ); ?>" class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-110" loading="lazy"><div class="absolute inset-0 bg-gradient-to-t from-ink/90 via-ink/10 to-transparent opacity-80 transition-opacity duration-500 group-hover:opacity-100"></div><div class="pointer-events-none absolute inset-0 border border-ivory/10"></div><figcaption class="absolute inset-x-0 bottom-0 translate-y-2 p-6 opacity-0 transition-all duration-500 group-hover:translate-y-0 group-hover:opacity-100"><span class="block font-serif text-2xl font-light text-ivory"><?php echo esc_html( $case['name'] ); ?></span><span class="text-[0.72rem] uppercase tracking-[0.18em] text-champagne"><?php echo esc_html( $case['note'] ); ?></span></figcaption></figure><?php endforeach; ?></div></div></section>
	<?php tbt_page_cta( 'Your story could be the next one we tell.', 'Start Your Story' ); ?>
</main>
<?php get_footer(); ?>
