<?php
/** @package TeethByTrev */
get_header();
$services = array(
	array( 'no' => '01', 'title' => 'Smile Makeovers', 'body' => 'A fully bespoke redesign of your smile. We study proportion, shade, and character against your face and personality, then build a plan that looks like the best version of you — never someone else.', 'points' => array( 'Digital smile preview', 'Custom shade & shape', 'Face-first design' ), 'image' => 'stock/service-smile-makeover.jpg', 'alt' => 'Dr. Trevor J. Thomas presenting a smile makeover plan to a patient', 'position' => 'object-top' ),
	array( 'no' => '02', 'title' => 'Porcelain Veneers', 'body' => 'Hand-finished ceramic artistry that corrects shape, color, and alignment with natural, light-catching translucency. Each veneer is layered by hand until it disappears into your smile.', 'points' => array( 'Minimal-prep options', 'Hand-layered ceramic', 'Lifelike translucency' ), 'image' => 'gallery/trev-veneer-craft.jpg', 'alt' => 'Porcelain veneer craftsmanship in the Teeth by Trev atelier' ),
	array( 'no' => '03', 'title' => 'Dental Implants', 'body' => 'Permanent, lifelike tooth replacement engineered for function and finished for beauty. From single teeth to full arches, implants restore your bite and your confidence for good.', 'points' => array( 'Single & full-arch', 'Guided placement', 'Restored function' ), 'image' => 'gallery/trev-intraoral-scan.jpg', 'alt' => 'Dental implant components beside a 3D arch rendering on screen' ),
	array( 'no' => '04', 'title' => 'Full-Mouth Rehabilitation', 'body' => 'Complex, life-restoring reconstruction that rebuilds health, bite, and confidence from the ground up. The most demanding work in dentistry, performed with patience and precision.', 'points' => array( 'Comprehensive plan', 'Bite & health restored', 'Staged for comfort' ), 'image' => 'gallery/trev-scan-suite.jpg', 'alt' => 'Full-mouth rehabilitation plan with 3D imaging and an implant model' ),
	array( 'no' => '05', 'title' => 'General Dentistry & Hygiene', 'body' => 'The foundation beneath every transformation. Routine cleanings, exams, and preventive care delivered with the same precision and calm as the artistry — because a beautiful smile begins with a healthy one.', 'points' => array( 'Cleanings & exams', 'Preventive care', 'Healthy foundation' ), 'image' => 'gallery/trev-consult-blue.jpg', 'alt' => 'The Teeth by Trev treatment studio, prepared for a hygiene visit' ),
);
?>
<main id="main-content" class="bg-onyx text-ivory">
	<?php tbt_page_hero( 'The Craft', 'Signature services, executed as artistry.', 'Every treatment is designed and finished by hand — proportion, translucency, and line drawn to your features.', 'gallery/trev-veneer-craft.jpg', 'Porcelain veneer craftsmanship in the Teeth by Trev atelier' ); ?>
	<section class="bg-onyx py-28 lg:py-40"><div class="mx-auto max-w-7xl space-y-28 px-6 lg:space-y-40 lg:px-10"><?php foreach ( $services as $i => $service ) : $reverse = 1 === $i % 2; ?><div class="grid items-center gap-12 lg:grid-cols-2 lg:gap-24"><div class="reveal <?php echo $reverse ? 'lg:order-2' : ''; ?>"><div class="relative aspect-[4/5] overflow-hidden"><img src="<?php echo tbt_asset( $service['image'] ); ?>" alt="<?php echo esc_attr( $service['alt'] ); ?>" class="h-full w-full object-cover <?php echo esc_attr( $service['position'] ?? 'object-center' ); ?>" loading="lazy"><div class="pointer-events-none absolute inset-0 border border-ivory/10"></div></div></div><div class="reveal <?php echo $reverse ? 'lg:order-1' : ''; ?>"><span class="font-serif text-5xl font-light leading-none text-gold/40"><?php echo esc_html( $service['no'] ); ?></span><h2 class="mt-6 font-serif text-4xl font-light leading-[1.1] text-ivory sm:text-5xl"><?php echo esc_html( $service['title'] ); ?></h2><p class="mt-6 max-w-md text-base leading-relaxed text-ivory/65 sm:text-lg"><?php echo esc_html( $service['body'] ); ?></p><ul class="mt-8 flex flex-wrap gap-x-8 gap-y-3"><?php foreach ( $service['points'] as $point ) : ?><li class="text-[0.72rem] uppercase tracking-[0.18em] text-ivory/55"><span class="mr-2 text-gold">—</span><?php echo esc_html( $point ); ?></li><?php endforeach; ?></ul></div></div><?php endforeach; ?></div></section>
	<?php tbt_experience_process(); ?>
	<?php tbt_page_cta( 'Not sure where to start? Let’s talk it through.' ); ?>
</main>
<?php get_footer(); ?>
