<?php
/** @package TeethByTrev */
get_header();
$benefits = array(
	array( 'title' => 'Plans from $0 down', 'body' => 'Begin your transformation today with low monthly payments tailored to your budget — no large upfront cost.', 'path' => 'M3 9.5h18M3 9.5A2.5 2.5 0 0 1 5.5 7h13A2.5 2.5 0 0 1 21 9.5m-18 0v7A2.5 2.5 0 0 0 5.5 19h13a2.5 2.5 0 0 0 2.5-2.5v-7M7 15.5h4' ),
	array( 'title' => 'Apply in minutes', 'body' => 'A simple, soft credit check gets you an answer fast — without affecting your score or interrupting your day.', 'path' => 'M12 7v5l3 2m6-2a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z' ),
	array( 'title' => 'Care that fits your life', 'body' => 'Stretch your investment across comfortable terms so the smile you deserve never has to wait for the perfect moment.', 'path' => 'M12 20.25S3.75 15.5 3.75 9.62A4.12 4.12 0 0 1 12 7.5a4.12 4.12 0 0 1 8.25 2.12C20.25 15.5 12 20.25 12 20.25Z' ),
);
$partners = array(
	array( 'name' => 'CareCredit', 'meta' => 'Most widely accepted', 'body' => 'The healthcare credit card accepted at practices nationwide, with special promotional financing on qualifying treatment.', 'href' => 'https://www.carecredit.com/go/276SNV/' ),
	array( 'name' => 'Alphaeon Credit', 'meta' => 'For elective care', 'body' => 'A dedicated credit card for cosmetic and elective care, offering flexible monthly plans and promotional offers.', 'href' => 'https://goalphaeon.com/apply?src=cling' ),
	array( 'name' => 'Cherry', 'meta' => 'Fast, soft-check approval', 'body' => 'Paperless approval in minutes with a soft credit check and flexible monthly payments — many patients qualify for 0% APR.', 'href' => 'https://pay.withcherry.com/trevor-jamal-thomas-dds-inc?utm_source=practice&m=51934' ),
	array( 'name' => 'Proceed Finance', 'meta' => 'For larger plans', 'body' => 'Built for comprehensive and full-mouth cases, with longer terms and higher approval amounts than standard cards.', 'href' => 'https://www.proceedfinance.com/application/create?referrer=37783-13017-4FDA' ),
);
$faqs = array(
	array( 'q' => 'Will checking my options affect my credit?', 'a' => 'No. Pre-qualification uses a soft credit check that has no impact on your credit score. You’ll see your options before committing to anything.' ),
	array( 'q' => 'What financing partners do you work with?', 'a' => 'We partner with CareCredit, Alphaeon, Cherry, and Proceed Finance — leading healthcare lenders offering plans with low and no-interest promotional periods. During your consultation we’ll match you to the right fit.' ),
	array( 'q' => 'Can I combine financing with insurance?', 'a' => 'Yes. Where applicable, we apply your benefits first and finance the remaining balance — so you only ever pay over time for what’s left.' ),
	array( 'q' => 'How long are the payment terms?', 'a' => 'Terms range from a few months to several years depending on the plan and treatment. We’ll walk you through options that keep your monthly payment comfortable.' ),
);
?>
<main id="main-content" class="bg-onyx text-ivory">
	<?php tbt_page_hero( 'Smile Now, Pay Later', 'A world-class smile shouldn’t wait.', 'Flexible financing and monthly payment plans make life-changing dentistry accessible — so you can begin today and pay over time.', 'stock/financing-hero.jpg', 'Reviewing a panoramic X-ray and dental implant model with a patient in the Teeth by Trev studio' ); ?>
	<section class="bg-onyx py-28 lg:py-40"><div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="reveal max-w-2xl"><p class="mb-6 text-[0.6rem] uppercase tracking-[0.34em] text-gold/70">01 — The Promise</p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ivory sm:text-5xl">Transformation, within reach.</h2></div><div class="mt-16 grid gap-x-12 gap-y-12 sm:grid-cols-3"><?php foreach ( $benefits as $benefit ) : ?><div class="reveal border-t border-ivory/15 pt-7"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" class="h-8 w-8 text-gold"><path d="<?php echo esc_attr( $benefit['path'] ); ?>" stroke-width="1.25"></path></svg><h3 class="mt-6 font-serif text-2xl font-light text-ivory"><?php echo esc_html( $benefit['title'] ); ?></h3><p class="mt-3 text-base leading-relaxed text-ivory/60"><?php echo esc_html( $benefit['body'] ); ?></p></div><?php endforeach; ?></div></div></section>
	<section class="border-t border-ivory/10 bg-ink py-28 lg:py-40"><div class="mx-auto max-w-7xl px-6 lg:px-10"><div class="reveal max-w-2xl"><p class="mb-6 text-[0.6rem] uppercase tracking-[0.34em] text-gold/70">02 — Our Partners</p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ivory sm:text-5xl">Trusted financing partners.</h2><p class="mt-6 max-w-xl text-base leading-relaxed text-ivory/60">We work with the most respected names in healthcare financing. Apply with any of them in minutes — most use a soft credit check that won’t affect your score.</p></div><div class="mt-16 grid gap-5 sm:grid-cols-2"><?php foreach ( $partners as $partner ) : ?><a href="<?php echo esc_url( $partner['href'] ); ?>" target="_blank" rel="noopener noreferrer" class="reveal group flex h-full flex-col border border-ivory/12 bg-white/[0.02] p-8 transition-colors duration-300 hover:border-gold/50"><span class="text-[0.6rem] uppercase tracking-[0.28em] text-gold/70"><?php echo esc_html( $partner['meta'] ); ?></span><h3 class="mt-4 font-serif text-3xl font-light text-ivory"><?php echo esc_html( $partner['name'] ); ?></h3><p class="mt-3 flex-1 text-base leading-relaxed text-ivory/60"><?php echo esc_html( $partner['body'] ); ?></p><span class="mt-6 inline-flex items-center gap-2 text-[0.72rem] uppercase tracking-[0.2em] text-ivory/70 transition-colors duration-300 group-hover:text-gold">Apply with <?php echo esc_html( $partner['name'] ); ?> <span class="transition-transform duration-300 group-hover:translate-x-1">→</span></span></a><?php endforeach; ?></div><p class="mt-8 text-[0.72rem] uppercase tracking-[0.18em] text-ivory/40">Not sure which fits? Dr. Trev’s team will match you to the right plan during your consultation.</p></div></section>
	<section class="border-t border-ivory/10 bg-onyx py-28 lg:py-40"><div class="mx-auto grid max-w-7xl gap-16 px-6 lg:grid-cols-[0.8fr_1fr] lg:gap-24 lg:px-10"><div class="reveal"><p class="mb-6 text-[0.6rem] uppercase tracking-[0.34em] text-gold/70">03 — Questions</p><h2 class="font-serif text-4xl font-light leading-[1.1] text-ivory sm:text-5xl">The details, answered.</h2></div><div class="divide-y divide-ivory/12 border-y border-ivory/12"><?php foreach ( $faqs as $faq ) : ?><div class="reveal py-8"><h3 class="font-serif text-2xl font-light text-ivory"><?php echo esc_html( $faq['q'] ); ?></h3><p class="mt-3 max-w-xl text-base leading-relaxed text-ivory/60"><?php echo esc_html( $faq['a'] ); ?></p></div><?php endforeach; ?></div></div></section>
	<?php tbt_page_cta( 'Let’s find a plan that fits your life.', 'Explore Financing Options' ); ?>
</main>
<?php get_footer(); ?>
