<?php
/** @package TeethByTrev */
$GLOBALS['tbt_minimal_header'] = array( 'path' => '/', 'label' => '← Home' );
get_header();
$options = array(
	array( 'kind' => 'In Person', 'slug' => 'in-person', 'eyebrow' => 'At the studio', 'body' => 'Sit chairside with Dr. Trev. A full clinical assessment, digital imaging, and a tailored plan — designed around your face, in the room where the work happens.', 'points' => array( 'Full clinical exam', 'Digital imaging & scans', 'Tailored treatment plan' ), 'icon' => 'M12 21s-6.5-5.4-6.5-10A6.5 6.5 0 0 1 18.5 11c0 4.6-6.5 10-6.5 10Z M12 11.5a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z' ),
	array( 'kind' => 'Video', 'slug' => 'video', 'eyebrow' => 'From anywhere', 'body' => 'A private virtual consultation by video. Share your goals and photos, and receive Dr. Trev’s expert perspective and direction — wherever you are in the world.', 'points' => array( 'Live video with Dr. Trev', 'Photo-based assessment', 'Clear next steps' ), 'icon' => 'M3.5 7.5A1.5 1.5 0 0 1 5 6h8a1.5 1.5 0 0 1 1.5 1.5v9A1.5 1.5 0 0 1 13 18H5a1.5 1.5 0 0 1-1.5-1.5Z M14.5 10.5l5-3v9l-5-3Z' ),
);
?>
<main id="main-content" class="min-h-screen bg-onyx text-ivory">
	<section class="relative overflow-hidden"><div class="tbt-top-glow absolute inset-0"></div><div class="relative mx-auto max-w-[1600px] px-6 pb-16 pt-40 lg:px-12 lg:pb-24 lg:pt-52"><div class="reveal"><p class="text-[0.62rem] uppercase tracking-[0.3em] text-gold">The Consultation</p><h1 class="mt-6 max-w-4xl font-serif text-5xl font-light leading-[1.04] text-ivory sm:text-6xl lg:text-7xl">Begin with a conversation.</h1><p class="mt-8 max-w-xl text-base leading-relaxed text-ivory/65 sm:text-lg">Every transformation starts here — an unhurried, expert assessment of where you are and the smile you imagine. Choose to meet in person or by video.</p></div></div></section>
	<section class="border-t border-ivory/10 bg-onyx py-20 lg:py-28"><div class="mx-auto grid max-w-[1600px] gap-6 px-6 lg:grid-cols-2 lg:gap-8 lg:px-12"><?php foreach ( $options as $option ) : ?><article class="reveal flex h-full flex-col border border-ivory/12 bg-ivory/[0.02] p-8 transition-colors duration-500 hover:border-gold/40 lg:p-12"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" class="h-9 w-9 text-gold"><path d="<?php echo esc_attr( $option['icon'] ); ?>"></path></svg><p class="mt-8 text-[0.62rem] uppercase tracking-[0.3em] text-gold/70"><?php echo esc_html( $option['eyebrow'] ); ?></p><h2 class="mt-3 font-serif text-3xl font-light text-ivory sm:text-4xl"><?php echo esc_html( $option['kind'] ); ?></h2><p class="mt-5 text-base leading-relaxed text-ivory/65"><?php echo esc_html( $option['body'] ); ?></p><ul class="mt-8 space-y-3"><?php foreach ( $option['points'] as $point ) : ?><li class="flex items-center gap-3 text-[0.72rem] uppercase tracking-[0.16em] text-ivory/55"><span class="text-gold">—</span><?php echo esc_html( $point ); ?></li><?php endforeach; ?></ul><div class="mt-10 flex items-center justify-between border-t border-ivory/10 pt-6"><span class="font-serif text-2xl font-light text-ivory">$250</span><a href="<?php echo esc_url( add_query_arg( 'type', $option['slug'], home_url( '/reserve/' ) ) ); ?>" class="group inline-flex items-center gap-3 border border-gold px-7 py-3.5 text-[0.66rem] uppercase tracking-[0.24em] text-gold transition-colors hover:bg-gold hover:text-onyx">Reserve <?php echo esc_html( $option['kind'] ); ?> <span class="transition-transform group-hover:translate-x-1">→</span></a></div></article><?php endforeach; ?></div><p class="reveal mx-auto mt-12 max-w-xl px-6 text-center text-[0.72rem] uppercase tracking-[0.2em] text-ivory/40">Consultations are by appointment and limited each month.</p></section>
</main>
<?php get_footer(); ?>
